name: Deploy
on: push
jobs:
  deploy:
#    strategy:
#      matrix:
##        version: [0.56.3, 0.57.2]
#        image: [ext-ubuntu]
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Hugo
        uses: klakegg/actions-hugo@1.0.0
        with:
#          version: ${{ matrix.version }}
          image: ext-ubuntu #${{ matrix.image }}
          source: src
        

#      - name: Setup hugo
#        uses: peaceiris/actions-hugo@v2
#        with:
#          hugo-version: '0.91.2+extended'
#          extended: true

#      - name: Build
#        # remove --minify tag if you do not need it
#        # docs: https://gohugo.io/hugo-pipes/minification/
#        run: |
#          cd src
#          ls -al
#          hugo 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
#            github_token: ${{ secrets.GITHUB_TOKEN }}
            personal_token: ${{ secrets.TOKEN }}
            external_repository: mamatias/mamatias.github.io
            publish_branch: main  # default: gh-pages
            publish_dir: ./src/public
            destination_dir: subdir